project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "posts_main.qmd"
    - "sql_course/index_sql.qmd"
    - "sql_course/1_introduction.qmd"
    - "sql_course/2_basics.qmd"
    - "sql_course/3_joins.qmd"
    - "sql_course/4_advanced.qmd"
    - "sql_course/5_subqueries.qmd"
    - "sql_course/6_DDL.qmd"
    - "sql_course/7_powerbi.qmd"
    - "sql_course/8_exercises.qmd"
    - "sql_course/Tennis_uitleg.qmd"
    - "sql_course/9_exercises_joins.qmd"
    - "sql_course/10_exercises_advanced.qmd"
    - "sql_course/11_exercises_subqueries.qmd"
    - "sql_course/12_exercise_DDL.qmd"
    - "sql_course/Bikestore_uitleg.qmd"
    - "posts_main/2024_05_18_My_first_blog/index.qmd"

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sql_course/index_sql.qmd
        text: "SQL cursus"
      - href: posts_main.qmd
        text: "Blog"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true