project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "SQL.qmd"

website:
  title: "DV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: SQL.qmd
        text: SQL_course

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true