project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "sql_course/index_sql.qmd"

website:
  title: "DV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sql_course/index_sql.qmd
        text: "SQL course"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true