project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "sql_course/index_sql.qmd"
    - "sql_course/1_introduction.qmd"
    - "sql_course/2_basics.qmd"
    - "sql_course/3_joins.qmd"
    - "sql_course/4_advanced.qmd"
    - "sql_course/5_subqueries.qmd"
    - "sql_course/6_DLL.qmd"
    - "sql_course/7_powerbi.qmd"

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sql_course/index_sql.qmd
        text: "SQL cursus"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true