---
title: "Basis van SQL"
author: Danny Volkaerts
date: last-modified
date-format: "DD MMM, YYYY" 
format:
  revealjs: 
    theme: default
filters:
  - interactive-sql
databases:
  - name: hr
    path: "https://raw.githubusercontent.com/dannyvolkaerts/something/main/hr.sql"
  - name: hr-not-editable
    path: "https://raw.githubusercontent.com/dannyvolkaerts/something/main/hr.sql"
    editable: false
---

### Topics

-   Basisstructuur SQL queries
-   SELECT statement om kolommen te halen van tabellen
-   WHERE clausule om rijen te filteren
-   Sorteren van het resultaat met ORDER BY


------------------------------------------------------------------------

### Basisstructuur

+------------------+---------------+
| Query            | Uitvoering    |
+:=================+:==============+
| **SELECT**\      | FROM\         |
| FROM\            | WHERE\        |
| WHERE\           | GROUP BY\     |
| GROUP BY\        | HAVING\       |
| HAVING\          | **SELECT**\   |
| ORDER BY\        | ORDER BY\     |
+------------------+---------------+

------------------------------------------------------------------------

### SELECT Statement

De SELECT-instructie wordt gebruikt om gegevens uit een database te selecteren. De geretourneerde gegevens worden opgeslagen in een resultatentabel, ook wel de result-set genoemd.

``` sql
SELECT column1, column2 
FROM table_name;
```

------------------------------------------------------------------------

### SELECT \*

De '\*' instructie wordt gebruikt om de volledige inhoud van de tabel te bekijken.

``` {.sql .interactive .hr}
SELECT * 
FROM regions;
```

------------------------------------------------------------------------

### WHERE Statement

De WHERE-statement wordt gebruikt om specifieke rijen te selecteren die voldoen aan één of meerdere voorwaarden.\

Voorbeeld: ik wil de werknemers (employees) met een salaris hoger dan 16000 euro.

``` {.sql .interactive .hr}
SELECT * 
FROM employees
WHERE salary > 16000;
```

::: notes
first_name as voornaam, last_name as achternaam, salary as salaris
:::

------------------------------------------------------------------------

### WHERE voorbeeld

Ik wil een overzicht van de werknemers (employees) die werken in het IT departement.

``` {.sql .interactive .hr}
-- we zoeken eerst de code voor het IT-departement
SELECT *
FROM departments;
-- daarna zoeken we de werknemers die binnen dit departement werken
SELECT first_name, last_name, department_id
FROM employees
WHERE department_id = '6';
```

------------------------------------------------------------------------

### WHERE - combineren

Combineren van filters kan met 'AND', 'OR', 'NOT'

Voorbeeld: Ik zoek de werknemers (employees) die werken in het IT departement EN een salaris hebben lager dan 18000 euro.

``` {.sql .interactive .hr}
SELECT first_name, last_name, department_id, salary
FROM employees
WHERE department_id = '6' 
AND salary < 18000;
```

------------------------------------------------------------------------

### WHERE - operatoren

=  !=   \>=   \>\
IN    LIKE    IS NULL    IS NOT NULL\

``` {.sql .interactive .hr}
SELECT first_name, last_name, salary
FROM employees
WHERE last_name LIKE 'Ma%'
```


:::{.notes}
SELECT *\
FROM employees\
WHERE phone_number IS NULL\
:::
------------------------------------------------------------------------

### SELECT DISTINCT

``` {.sql .interactive .hr}
SELECT DISTINCT salary
FROM employees
```

------------------------------------------------------------------------

### SELECT functies

| Operatie  | Definitie                 |
|-----------|---------------------------|
| COUNT     | Aantal lijnen             |
| AVG       | Gemiddelde van de waarden |
| SUM       | Som van de waarden        |
| MIN / MAX | Minimum / Maximum waarde  |

------------------------------------------------------------------------

### SELECT functies voorbeeld

Hoeveel werknemers in het IT departement?

``` {.sql .interactive .hr}
SELECT department_id, count(*)
FROM employees
WHERE department_id = '6' 
```

:::{.notes}

SELECT department_id\
FROM employees\
WHERE department_id = '6'\

SELECT department_id, count(*) as aantal\
FROM employees\
WHERE department_id = '6'\
:::

---

### Oefeningen
