---
title: "SQL Course"
format: 
  html:
    embed-resources: true
---

SQL, or Structured Query Language, is a standardized programming language used to manage and manipulate relational databases. Understanding SQL opens opportunities in data analysis, data engineering, and beyond, making it an essential skill for any aspiring data professional. It enables data professionals to derive meaningful insights from large datasets, perform data analyses, and input data into their machine learning models.\

SQL was developed in the 1970s and has since become the universal language for relational database management systems (RDBMS) like MySQL, PostgreSQL, SQLite, and Microsoft SQL Server. It is widely used in data science, software development, and business intelligence for tasks such as:\

**Data Retrieval**: Extracting specific information from large datasets using SELECT statements.\
**Data Manipulation**: Modifying data with commands like INSERT, UPDATE, and DELETE.\
**Data Definition**: Creating and managing database structures with CREATE, ALTER, and DROP.\
**Data Analysis**: Aggregating and analyzing data using functions like GROUP BY, HAVING, and COUNT.\

SQL's simplicity and power make it an indispensable tool for professionals working with data, enabling efficient data management and analysis across industries.\


> Tell me and I forget, teach me and I may remember, involve me and I learn.\
– Benjamin Franklin

## Chapters
1. [**Introduction to SQL and Databases**](1_introduction.html){target="_blank"}\
Overview of SQL, databases, and how they are used in data science.

---

2. [**Basic SQL Queries**](2_basics.html){target="_blank"}\ 
Learning SELECT statements and filtering data with WHERE clauses.

---

3. [**Working with Table Joins**](3_joins.html){target="_blank"} \
Introduction to JOIN operations and their importance.

---

4. [**Advanced Data Manipulation**](4_advanced.html){target="_blank"}\
Using GROUP BY, HAVING, and aggregate functions.

---

5. [**Subqueries, Nested Queries, and Views**](5_subqueries.html){target="_blank"}\
Extending queries with subqueries for more complex data retrieval.

---

6. [**Data Definition Language (DDL) & Data Manipulation Language (DML)**](6_DDL.html){target="_blank"}\
Understanding how to create a database and insert, update, and delete data in the database.

---

7. [**SQL and PowerBI**](7_powerbi.html){target="_blank"}\
Extracting insights from data by combining the power of SQL with PowerBI.

---

8. [**Exercises Chapter 1 and 2**](8_exercises.html){target="_blank"}\
Exercises for chapters 1 and 2.

---

9. [**Exercises Chapter 3**](9_exercises_joins.html){target="_blank"}\
Exercises for chapter 3 - joins.

---

10. [**Exercises Chapter 4**](10_exercises_advanced.html){target="_blank"}\
Exercises for chapter 4 - GROUP BY, HAVING, etc.

---

11. [**Exercises Chapter 5**](11_exercises_subqueries.html){target="_blank"}\
Exercises for chapter 5 - subqueries.

---

12. [**Exercises Chapter 6**](12_exercise_DDL.html){target="_blank"}\
Exercises for DDL - the bike shop.
